# Numpy 

## Array Creation

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

- **ndarray.ndim**
    the number of axes (dimensions) of the array.
- **ndarray.shape**
    the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
- **ndarray.size**
    the total number of elements of the array. This is equal to the product of the elements of shape.
- **ndarray.dtype**
    an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
- **ndarray.itemsize**
    the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
- **ndarray.data**
    the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities. 

In [20]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.size

15

In [6]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [13]:
b.dtype

dtype('int64')

In [14]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

The type of the array can also be explicitly specified at creation time:

In [16]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

The function zeros creates an array full of **zeros**, the function ones creates an array full of **ones**, and the function **empty** creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is **float64**.

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,3,4), dtype=np.int16)                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty((2,3))                                 # uninitialized, output may vary

array([[4.6536661e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

When **arange** is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function **linspace** that receives as an argument the number of elements that we want, instead of the step

In [ ]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [76]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [79]:
c = a-b
c

array([20, 29, 38, 47])

In [29]:
b**2

array([0, 1, 4, 9])

In [30]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [31]:
a<35

array([ True,  True, False, False])

In [32]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )

In [33]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [34]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [35]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [36]:
a = np.random.random((2,3))
a

array([[0.61114523, 0.33226733, 0.26441755],
       [0.2634804 , 0.75983077, 0.62013416]])

In [37]:
a.sum()

2.8512754254069455

In [38]:
a.min()

0.2634804003021186

In [39]:
a.max()

0.7598307680713321

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array

In [40]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [42]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [43]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [44]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [45]:
a[2]

8

In [46]:
a[2:5]

array([ 8, 27, 64])

In [47]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [48]:
a[ : :-1]                                 # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

## Changing the shape of an array

In [53]:
a = np.floor(10*np.random.random((3,4)))
a.ravel()  # returns the array, flattened

array([6., 4., 4., 3., 3., 5., 8., 8., 5., 9., 2., 1.])

In [55]:
a.reshape(6,2)  # returns the array with a modified shape

array([[6., 4.],
       [4., 3.],
       [3., 5.],
       [8., 8.],
       [5., 9.],
       [2., 1.]])

In [56]:
a.T  # returns the array, transposed

array([[6., 3., 5.],
       [4., 5., 9.],
       [4., 8., 2.],
       [3., 8., 1.]])

In [57]:
a.T.shape

(4, 3)

In [58]:
a.shape

(3, 4)

## No Copy at All

In [59]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [61]:
b.shape = 3,4    # changes the shape of a
a.shape

(3, 4)

## View or Shallow Copy¶

In [62]:
c = a.view()
c is a

False

In [63]:
c.base is a                        # c is a view of the data owned by a

True

In [64]:
c.shape = 2,6                      # a's shape doesn't change
a.shape

(3, 4)

In [65]:
c[0,4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

## Deep Copy

In [66]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [67]:
d.base is a                           # d doesn't share anything with a

False

In [68]:
d[0,0] = 9999
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

## Fancy indexing and index tricks
- NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

In [69]:
a = np.arange(12)**2                       # the first 12 square numbers
i = np.array( [ 1,1,3,8,5 ] )              # an array of indices
a[i]                                       # the elements of a at the positions i

array([ 1,  1,  9, 64, 25])

In [70]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )      # a bidimensional array of indices
a[j]                                       # the same shape as j

array([[ 9, 16],
       [81, 49]])

## Indexing with Boolean Arrays

- When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t. The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array

In [71]:
a = np.arange(12).reshape(3,4)
b = a > 4
b                                          # b is a boolean with a's shape

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
a[b]                                       # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

## Linear Algebra

### Eigen values & vectors
- The set of eigenvectors of a matrix is a special set of input vectors for which  the  action  of  the  matrix  is  described  as  a  simplescaling.  When a  matrix  is  multiplied  by  one  of  its  eigenvectors  the  output  is  the  same eigenvector multiplied by a constant Ae = λe. The constant λ is called an eigenvalue of A.

In [81]:
from numpy import linalg as LA

w, v = LA.eig(np.diag((1, 2, 3)))
w

array([1., 2., 3.])

In [82]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Solve Equations

In [83]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [88]:
LA.inv(a)

array([[-3.],
       [ 4.]])

In [87]:
y = np.array([[5.], [7.]])
LA.solve(a, y)

array([[-3.],
       [ 4.]])

In [89]:
LA.inv(a) @ y

array([[-3.],
       [ 4.]])